version: '3.8'

services:
  drizzle-plus-postgres:
    image: postgres:18beta1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - '0:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d testdb']
      interval: 5s
      timeout: 5s
      retries: 5

  drizzle-plus-mysql:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - '0:3306'
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-ppassword',
        ]
      interval: 5s
      timeout: 5s
      retries: 5
